### PR TITLE
[TOOL-154] Add transform function for processing timeline data

### PR DESCRIPTION
**Pull request by dejan-crocoder**

### CODE REVIEW

**Review by Ante-Koceic — COMMENTED** [review]
This is a review

**Review by Ante-Koceic — DISMISSED** [review]
Approved?

**Review by Ante-Koceic — APPROVED** [review]

**Review by Ante-Koceic — APPROVED** [review]
Comment

**Comment by dejan-crocoder** [comment]
moved to #306

**Pull request closed without merging**
